Repository 36-APPJAM-HEARTZ/ByeBoo-ANDROID, pull requests merged in 2025-09, with the labels that each got.

#167 [feat/#165] 로컬에 닉네임, 여정 상태 정보 저장
  app/src/main/java/com/byeboo/app/data/datasource/local/UserLocalDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/local/UserLocalDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/dto/response/auth/KakaoLoginResponseDto.kt
  app/src/main/java/com/byeboo/app/data/mapper/auth/AuthMapper.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/quest/QuestStateRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/domain/model/auth/AuthResult.kt
  app/src/main/java/com/byeboo/app/domain/repository/quest/QuestStateRepository.kt
  app/src/main/java/com/byeboo/app/domain/usecase/LoginUseCase.kt
Labels: 🍒 [FEAT], 🐰 아연

#170 [feat/#169] 자동 로그인 구현
  app/src/main/java/com/byeboo/app/domain/usecase/LoginUseCase.kt
  app/src/main/java/com/byeboo/app/domain/usecase/ReissueAccessTokenUseCase.kt
  app/src/main/java/com/byeboo/app/presentation/splash/SplashScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/SplashState.kt
  app/src/main/java/com/byeboo/app/presentation/splash/SplashViewModel.kt
Labels: 🍒 [FEAT], 🐰 아연

#171 [feat/#162] 닉네임 변경 api 연동
  app/src/main/java/com/byeboo/app/data/datasource/remote/auth/UserRemoteDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/auth/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/dto/request/auth/UserNicknameRequestDto.kt
  app/src/main/java/com/byeboo/app/data/dto/response/auth/UserNicknameChangeResponseDto.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/auth/UserRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/auth/UserService.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/editprofile/EditProfileScreen.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/editprofile/EditProfileViewModel.kt
Labels: 🌎 서버 통신, 🍒 [FEAT], 🐰 아연

#177 [feat/#168] 로그아웃, 회원탈퇴 api 연동
  app/src/main/java/com/byeboo/app/data/datasource/local/TokenDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasource/remote/auth/AuthRemoteDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/local/TokenDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/auth/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/auth/TokenRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/auth/AuthService.kt
  app/src/main/java/com/byeboo/app/domain/repository/auth/AuthRepository.kt
  app/src/main/java/com/byeboo/app/domain/repository/auth/TokenRepository.kt
  app/src/main/java/com/byeboo/app/domain/usecase/LogoutUseCase.kt
  app/src/main/java/com/byeboo/app/domain/usecase/WithdrawUseCase.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/MyPageState.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/MypageViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/navigation/MypageNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/splash/navigation/SplashNavigation.kt
Labels: 🌎 서버 통신, 🍒 [FEAT], 🐰 아연

#186 [fix/#181] 새로운 여정 시작하기 api 호출 시점 변경
  app/src/main/java/com/byeboo/app/data/datasource/remote/NewJourneyDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasource/remote/offboarding/OffboardingNewJourneyDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/NewJourneyDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/offboarding/OffboardingNewJourneyDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/di/DataSourceModule.kt
  app/src/main/java/com/byeboo/app/data/di/RepositoryModule.kt
  app/src/main/java/com/byeboo/app/data/di/ServiceModule.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/NewJourneyRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/offboarding/OffboardingNewJourneyRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/NewJourneyService.kt
  app/src/main/java/com/byeboo/app/domain/model/JourneyStatus.kt
  app/src/main/java/com/byeboo/app/domain/repository/NewJourneyRepository.kt
  app/src/main/java/com/byeboo/app/domain/repository/offboarding/OffboardingNewJourneyRepository.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeUiState.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainScreen.kt
  app/src/main/java/com/byeboo/app/presentation/mypage/editprofile/EditProfileScreen.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/navigation/OffboardingNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingcompletedguide/OffboardingCompletedGuideScreen.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingnewjourney/OffboardingNewJourneyScreen.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingnewjourney/OffboardingNewJourneyState.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingnewjourney/OffboardingNewJourneyViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingquestcompleted/OffboardingQuestCompletedScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestRoute.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartViewModel.kt
Labels: 🐶 소희, 🔧 [FIX]

#189 [fix/#187] 퀘스트, 오프보딩 화면 에러 핸들링
  app/src/main/java/com/byeboo/app/presentation/offboarding/OffboardingJourneyState.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/OffboardingJourneyViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingcompletedjourney/OffboardingCompletedJourneyScreen.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingquestcompleted/OffboardingQuestCompletedScreen.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingquestcompleted/OffboardingQuestCompletedState.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingquestcompleted/OffboardingQuestCompletedViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorWritingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/model/QuestState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingCompleteState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingCompleteViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/review/QuestReviewScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/review/QuestReviewState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/review/QuestReviewViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/tip/QuestTipScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/tip/QuestTipState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/tip/QuestTipViewModel.kt
Labels: 🐶 소희, 🔧 [FIX]

#200 [qa/#199] 배경 수정 및 홈 화면 로띠 수정
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/res/drawable/bg_home.png
  app/src/main/res/drawable/bg_userinfo.png
  app/src/main/res/raw/bori_home.json
Labels: 🦊 종훈, 🛠️ [CHORE]

#201 [qa/#197] 1차 qa 추가 수정사항 반영
  app/src/main/java/com/byeboo/app/domain/model/auth/NicknameValidator.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
Labels: 🐶 소희, 🛠️ [CHORE]

#198 [feat/#196] proguard설정 및 키스토어 공유
  app/build.gradle.kts
Labels: 🍒 [FEAT], 🦊 종훈

#205 [qa/#203] 2차 qa
  app/src/main/java/com/byeboo/app/core/designsystem/component/tag/SmallTag.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/text/ContentText.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeAmuletCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeQuestCard.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingcompletedguide/OffboardingCompletedGuideScreen.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/offboardingnewjourney/OffboardingNewJourneyScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/card/QuestCompleteCard.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/card/QuestEmotionDescriptionCard.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/modal/QuestGuideModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/modal/QuestQuitModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/text/textfield/QuestTextField.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/type/QuestContentType.kt
  app/src/main/java/com/byeboo/app/presentation/quest/model/QuestState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/tip/QuestTipScreen.kt
  app/src/main/res/drawable/ic_caution.xml
  app/src/main/res/drawable/ic_shoe.xml
Labels: 🐶 소희, 🛠️ [CHORE]
