Repository 36-APPJAM-HEARTZ/ByeBoo-ANDROID, pull requests merged in 2025-08, with the labels that each got.

#118 [fix/#117] 네비 오류 해결 & 변수 상태 변경
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/navigation/QuestBehaviorNavigation.kt
Labels: 🐶 소희, 🔧 [FIX]

#120 [refactor/#119] screen, route 분리
  app/src/main/java/com/byeboo/app/presentation/quest/component/bottomsheet/ByeBooBottomSheet.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/navigation/QuestRecordNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/review/QuestReviewScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/tip/QuestTipScreen.kt
Labels: 🌈 [REFACTOR], 🐶 소희

#136 [mod/#132] 홈 온보딩, 홈 화면 디자인 변경 사항 반영
  app/src/main/java/com/byeboo/app/data/datasource/local/UserLocalDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/local/UserLocalDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/auth/UserRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/domain/repository/auth/UserRepository.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeUiState.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeAmuletCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeSpeechBubbleText.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeTextCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeonboarding/HomeOnboardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/navigation/HomeNavigation.kt
  app/src/main/res/drawable/ic_home_about_bori.xml
  app/src/main/res/drawable/ic_home_question.xml
  app/src/main/res/drawable/ic_home_speech_bubble.xml
  app/src/main/res/drawable/ic_speech_bubble.xml
  app/src/main/res/drawable/img_active_amulet_back.png
  app/src/main/res/drawable/img_active_amulet_front.png
  app/src/main/res/drawable/img_recording_amulet_back.png
  app/src/main/res/drawable/img_recording_amulet_front.png
  app/src/main/res/drawable/speech_bubble.xml
Labels: 🌈 [REFACTOR], 🦊 종훈

#138 [mod/#128] 디자인 수정 반영
  app/src/main/java/com/byeboo/app/core/designsystem/component/button/ByeBooButton.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorWritingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/chip/QuestEmotionChip.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/modal/QuestQuitModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/text/CreatedText.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/text/QuestTitle.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingScreen.kt
  app/src/main/res/drawable/ic_think.xml
Labels: 🐰 아연, 🛠️ [CHORE]

#144 [Feat/#137] 로그인, 이용 약관 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/byeboo/app/core/designsystem/ui/theme/Color.kt
  app/src/main/java/com/byeboo/app/core/util/OpenUrlExt.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/splash/SplashScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermType.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermsOfServiceScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermsOfServiceState.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermsOfServiceViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/component/TermsAllButton.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/component/TermsCheckButton.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/navigation/TermsNavigation.kt
  app/src/main/res/drawable/ic_kakao_logo.xml
  app/src/main/res/drawable/ic_terms_checked.xml
  app/src/main/res/drawable/ic_terms_unchecked.xml
  gradle/libs.versions.toml
Labels: 🍒 [FEAT], 🍥 [UI], 🐰 아연

#149 [mod/#148] 마이페이지 수정
  app/src/main/java/com/byeboo/app/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermsOfServiceScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermsOfServiceState.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/TermsOfServiceViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/splash/termsofservice/component/TermsAllButton.kt
Labels: 🐶 소희

#155 [feat/#153] 에러 핸들링
  app/src/main/java/com/byeboo/app/core/designsystem/component/snackbar/CustomSnackBar.kt
  app/src/main/java/com/byeboo/app/core/designsystem/event/SnackbarTrigger.kt
  app/src/main/java/com/byeboo/app/core/state/UiState.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/quest/QuestStateRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/auth/UserService.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletState.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/start/QuestStartViewModel.kt
  app/src/main/res/drawable/ic_alert.xml
Labels: 🍒 [FEAT], 🦊 종훈

#163 [mod/#159] 로띠 추가 및 말풍선 사이즈 조정
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeSpeechBubbleText.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeonboarding/HomeOnboardingScreen.kt
  app/src/main/res/raw/bori_onboarding.json
Labels: 🦊 종훈, 🛠️ [CHORE]
