Repository 36-APPJAM-HEARTZ/ByeBoo-ANDROID, pull requests merged in 2025-07, with the labels that each got.

#12 [add/#11 ] add svg icon
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_double_check.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_left.xml
  app/src/main/res/drawable/ic_letter_closed.xml
  app/src/main/res/drawable/ic_letter_opened.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_reset.xml
  app/src/main/res/drawable/ic_right.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_up.xml
Labels: ➕ [ADD], 🐶 소희

#14 [add/#13] add opacity color
  app/src/main/java/com/byeboo/app/core/designsystem/ui/theme/Color.kt
  app/src/main/java/com/byeboo/app/core/designsystem/ui/theme/TypoGraphy.kt
Labels: ➕ [ADD], 🐶 소희

#19 [docs/#18] Readme 작성
  README.md
Labels: 🐰 아연, 📄 [DOCS]

#22 [feat/#15] 공통 컴포넌트 구현 - Tag, Chip, BottomSheet 등
  app/build.gradle.kts
  app/src/main/java/com/byeboo/app/core/designsystem/component/button/ByeBooActivationButton.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/button/ByeBooButton.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/chip/EmotionChip.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/contenttext/ContentText.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/line/ByeBooLine.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/tag/LargeTag.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/tag/MiddleTag.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/tag/SmallTag.kt
  app/src/main/java/com/byeboo/app/core/designsystem/type/LargeTagType.kt
  app/src/main/java/com/byeboo/app/core/designsystem/type/MiddleTagType.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/component/OffboardingIconButton.kt
  app/src/main/java/com/byeboo/app/presentation/offboarding/component/OffboardingModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestWritingState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestCompleteCard.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestContent.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestEmotionDescriptionCard.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestGuideContent.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestJourneyTitle.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestStepTitle.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestTextField.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestTitle.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuitModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/bottomsheet/ByeBooBottomSheet.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/bottomsheet/ByeBooDragHandle.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/type/JourneyType.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/type/QuestContentType.kt
  app/src/main/res/drawable/ic_change.xml
  app/src/main/res/drawable/ic_think.xml
  app/src/main/res/drawable/ic_tip_write.xml
  app/src/main/res/drawable/img_congrate.png
  app/src/main/res/drawable/img_neutral.png
  app/src/main/res/drawable/img_relief.png
  app/src/main/res/drawable/img_sadness.png
  app/src/main/res/drawable/img_self_aware.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🍒 [FEAT], 🐰 아연

#25 [feat/#17] 정보입력 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/byeboo/app/ByeBoo.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/button/ByeBooActivationButton.kt
  app/src/main/java/com/byeboo/app/core/designsystem/component/topbar/ByeBooTopBar.kt
  app/src/main/java/com/byeboo/app/core/designsystem/ui/theme/Theme.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/navigation/LoadingNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/nickname/ValidationState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/onboarding/OnboardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/component/NicknameTextField.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/component/UserInfoEmotionCard.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/component/UserInfoProgressBar.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/component/UserInfoQuestCard.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/component/UserInfoText.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/model/UserInfoItem.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/model/UserInfoValidationState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/navigation/UserInfoNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/screen/UserInfoEmotionScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/screen/UserInfoNicknameScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/screen/UserInfoQuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainActivity.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainScreen.kt
  app/src/main/java/com/byeboo/app/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestGuideContent.kt
  app/src/main/res/drawable/bg_userinfo.png
  app/src/main/res/drawable/ic_book.png
  app/src/main/res/drawable/ic_emotion_good.png
  app/src/main/res/drawable/ic_emotion_sad.png
  app/src/main/res/drawable/ic_emotion_soso.png
  app/src/main/res/drawable/ic_shoes.png
  app/src/main/res/drawable/ic_user_loading.png
  app/src/main/res/raw/loading_byeboo.json
  gradle/libs.versions.toml
Labels: 🍒 [FEAT], 🦊 종훈

#30 [feat/#29] 온보딩 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/byeboo/app/presentation/splash/OnBoardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/OnBoardingState.kt
  app/src/main/java/com/byeboo/app/presentation/splash/OnBoardingViewModel.kt
  app/src/main/res/drawable/img_onboarding_1st.png
  app/src/main/res/drawable/img_onboarding_2nd.png
  app/src/main/res/drawable/img_onboarding_3rd.png
  app/src/main/res/drawable/img_onboarding_4th.png
  app/src/main/res/drawable/img_onboarding_5th.png
Labels: 🍥 [UI], 🐰 아연

#35 [feat/#32] 홈 UI 구현
  app/src/main/java/com/byeboo/app/core/util/ModifierExt.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/navigation/LoadingNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/navigation/AuthNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/navigation/UserInfoNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeProgressCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeQuestCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeTextCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeonboarding/HomeOnboardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/res/drawable/home_onboarding.png
  app/src/main/res/drawable/speech_bubble.xml
Labels: 🍒 [FEAT], 🍥 [UI], 🦊 종훈

#40 [FIX/#38] 온보딩->홈까지 전반적인 로직 수정
  app/src/main/java/com/byeboo/app/core/util/ModifierExt.kt
  app/src/main/java/com/byeboo/app/presentation/auth/journeyResult/navigatioin/JourneyResultNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/auth/navigation/AuthNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/onboarding/OnboardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/auth/onboarding/OnboardingState.kt
  app/src/main/java/com/byeboo/app/presentation/auth/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/auth/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeQuestCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeTextCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletState.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeonboarding/HomeOnboardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorCompleteScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/bottomsheet/ByeBooBottomSheet.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/splash/OnBoardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/OnBoardingState.kt
  app/src/main/java/com/byeboo/app/presentation/splash/OnBoardingViewModel.kt
Labels: 🦊 종훈, 🔧 [FIX]

#58 [hotfix/#57] : MyPage UI 수정
  app/src/main/java/com/byeboo/app/presentation/mypage/MypageScreen.kt
Labels: 🐶 소희, 🔧 [FIX]

#61 [feat/#55] quest tip api
  app/src/main/java/com/byeboo/app/data/datasource/remote/quest/QuestStateDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasource/remote/quest/QuestTipDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/QuestStateDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/QuestTipDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/di/DataSourceModule.kt
  app/src/main/java/com/byeboo/app/data/di/RepositoryModule.kt
  app/src/main/java/com/byeboo/app/data/di/ServiceModule.kt
  app/src/main/java/com/byeboo/app/data/dto/request/QuestRequestDto.kt
  app/src/main/java/com/byeboo/app/data/dto/response/QuestTipResponseDto.kt
  app/src/main/java/com/byeboo/app/data/mapper/quest/QuestTipMapper.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/quest/QuestStateRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/quest/QuestTipRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/quest/QuestService.kt
  app/src/main/java/com/byeboo/app/data/service/quest/QuestTipService.kt
  app/src/main/java/com/byeboo/app/domain/model/quest/QuestTipModel.kt
  app/src/main/java/com/byeboo/app/domain/repository/QuestBehaviorRepository.kt
  app/src/main/java/com/byeboo/app/domain/repository/UserRepository.kt
  app/src/main/java/com/byeboo/app/domain/repository/quest/QuestStateRepository.kt
  app/src/main/java/com/byeboo/app/domain/repository/quest/QuestTipRepository.kt
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/UserInfoViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestStartViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/util/navigateToQuestClearBackStack.kt
Labels: 🍒 [FEAT], 🐶 소희

#67 [feat#59] : quest home api
  app/src/main/java/com/byeboo/app/core/model/QuestType.kt
  app/src/main/java/com/byeboo/app/data/datasource/local/DummyLocalDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasource/remote/DummyRemoteDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasource/remote/QuestInProgressDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/local/DummyLocalDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/DummyRemoteDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/QuestInProgressDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/di/DataSourceModule.kt
  app/src/main/java/com/byeboo/app/data/di/RepositoryModule.kt
  app/src/main/java/com/byeboo/app/data/di/ServiceModule.kt
  app/src/main/java/com/byeboo/app/data/dto/base/DummyBaseResponse.kt
  app/src/main/java/com/byeboo/app/data/dto/base/DummyNullableBaseResponse.kt
  app/src/main/java/com/byeboo/app/data/dto/request/RequestDummyDto.kt
  app/src/main/java/com/byeboo/app/data/dto/response/QuestInProgressResponseDto.kt
  app/src/main/java/com/byeboo/app/data/mapper/QuestInProgressMapper.kt
  app/src/main/java/com/byeboo/app/data/mapper/UserInfoMapper.kt
  app/src/main/java/com/byeboo/app/data/mapper/todata/DummyMapper.kt
  app/src/main/java/com/byeboo/app/data/mapper/todomain/ResponseDummyDtoMapper.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/QuestInProgressRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/DummyService.kt
  app/src/main/java/com/byeboo/app/data/service/quest/QuestService.kt
  app/src/main/java/com/byeboo/app/domain/model/Dummy.kt
  app/src/main/java/com/byeboo/app/domain/model/DummyResultModel.kt
  app/src/main/java/com/byeboo/app/domain/model/quest/QuestInProgressModel.kt
  app/src/main/java/com/byeboo/app/domain/model/quest/QuestStateModel.kt
  app/src/main/java/com/byeboo/app/domain/repository/DummyRepository.kt
  app/src/main/java/com/byeboo/app/domain/repository/QuestInProgressRepository.kt
  app/src/main/java/com/byeboo/app/domain/usecase/DummyUseCase.kt
  app/src/main/java/com/byeboo/app/presentation/home/HomeViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeonboarding/HomeOnboardingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestReviewScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestReviewState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestUiState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestJourneyTitle.kt
  app/src/main/java/com/byeboo/app/presentation/quest/component/QuestModal.kt
  app/src/main/java/com/byeboo/app/presentation/quest/model/QuestModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
Labels: 🌎 서버 통신, 🍒 [FEAT], 🦊 종훈

#77 [chore/#68] 스플래시, 부적 온보딩 변경
  app/src/main/java/com/byeboo/app/core/model/QuestType.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/local/UserLocalDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/domain/model/quest/QuestData.kt
  app/src/main/java/com/byeboo/app/domain/usecase/QuestUseCase.kt
  app/src/main/java/com/byeboo/app/presentation/auth/loading/LoadingViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/auth/navigation/AuthNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/home/component/HomeAmuletCard.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletScreen.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletState.kt
  app/src/main/java/com/byeboo/app/presentation/home/homeamulet/HomeAmuletViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavHost.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainNavigator.kt
  app/src/main/java/com/byeboo/app/presentation/main/MainScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestTipScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestUiState.kt
  app/src/main/java/com/byeboo/app/presentation/quest/QuestViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/navigation/QuestNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/util/navigateToQuestClearBackStack.kt
  app/src/main/java/com/byeboo/app/presentation/splash/SplashScreen.kt
  app/src/main/java/com/byeboo/app/presentation/splash/navigation/SplashNavigation.kt
  app/src/main/res/drawable/img_active_amulet_back.png
  app/src/main/res/drawable/img_active_amulet_front.png
  app/src/main/res/drawable/img_emotion_face.png
  app/src/main/res/drawable/img_emotion_organize.png
  app/src/main/res/drawable/img_recording_amulet_back.png
  app/src/main/res/drawable/img_recording_amulet_front.png
  app/src/main/res/drawable/img_splash_background.png
  app/src/main/res/drawable/img_splash_logo.png
Labels: 🍒 [FEAT], 🦊 종훈, 🛠️ [CHORE]

#78 [feat/#60] quest behavior writing api 연동
  app/src/main/java/com/byeboo/app/data/datasource/remote/QuestBehaviorAnswerDataSource.kt
  app/src/main/java/com/byeboo/app/data/datasourceimpl/remote/QuestBehaviorAnswerDataSourceImpl.kt
  app/src/main/java/com/byeboo/app/data/di/DataSourceModule.kt
  app/src/main/java/com/byeboo/app/data/di/RepositoryModule.kt
  app/src/main/java/com/byeboo/app/data/di/ServiceModule.kt
  app/src/main/java/com/byeboo/app/data/dto/request/QuestBehaviorAnswerRequestDto.kt
  app/src/main/java/com/byeboo/app/data/dto/request/QuestSignedUrlRequestDto.kt
  app/src/main/java/com/byeboo/app/data/dto/response/QuestSingedUrlResponseDto.kt
  app/src/main/java/com/byeboo/app/data/mapper/quest/QuestBehaviorMapper.kt
  app/src/main/java/com/byeboo/app/data/mapper/todata/QuestEmotionMapper.kt
  app/src/main/java/com/byeboo/app/data/repositoryimpl/QuestBehaviorAnswerRepositoryImpl.kt
  app/src/main/java/com/byeboo/app/data/service/quest/QuestBehaviorService.kt
  app/src/main/java/com/byeboo/app/domain/model/QuestBehaviorModel.kt
  app/src/main/java/com/byeboo/app/domain/repository/QuestBehaviorAnswerRepository.kt
  app/src/main/java/com/byeboo/app/domain/usecase/UploadImageUseCase.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorViewModel.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/QuestBehaviorWritingScreen.kt
  app/src/main/java/com/byeboo/app/presentation/quest/behavior/navigation/QuestBehaviorNavigation.kt
  app/src/main/java/com/byeboo/app/presentation/quest/record/QuestRecordingCompleteScreen.kt
Labels: 🌎 서버 통신, 🍒 [FEAT], 🐰 아연

#93 [QA/#92] 온보딩 디자인 QA 반영
  app/src/main/java/com/byeboo/app/presentation/auth/userinfo/component/NicknameTextField.kt
Labels: 🍥 [UI], 🐰 아연
